# -*- coding: utf-8 -*-
"""EDA_All E-Commers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nhhTBVsrrPnhCdj_reocBVSsM5B57nLa

# 📊 EDA E-Commerce — Analisis Eksplorasi Dataset Smartphone
> **Dataset:** `ecommerce_clean_merged.csv` — gabungan data listing smartphone dari Shopee, Lazada, dan Tokopedia  
> **Tujuan:** Memahami distribusi harga, penjualan, rating, dan perilaku pasar per brand dan per platform  
> **Author:** Raissa | Multi-Platform Big Data Analysis

## 1. Import Library & Load Data
"""

pip install pandas matplotlib seaborn numpy jupyter

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# setting visual
sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (10,6)

"""### Load Dataset"""

df = pd.read_csv("ecommerce_clean_merged.csv")

df = df[
    ~df['Brand_Ekstrak'].isin(['non_smartphone','other'])
]

df.head()

"""### Informasi Struktur Data"""

df.info()

df.isnull().sum()

df.describe()

"""> **Insight:** Dataset memiliki 4.433 baris produk smartphone dari 3 marketplace setelah proses cleaning.  
> Missing value = 0, tipe data sudah sesuai hasil preprocessing.

---
## 2. Analisis per Brand

Bagian ini menganalisis distribusi harga, jumlah listing, dan penjualan berdasarkan brand smartphone.

### 2.1 Distribusi Harga per Brand
Boxplot menampilkan sebaran harga (min, Q1, median, Q3, max) untuk setiap brand.  
Brand dengan boxplot tinggi dan lebar menunjukkan variasi harga yang besar (ada varian entry-level hingga premium).
"""

top_brand = df['Brand_Ekstrak'].value_counts().head(10).index

df_top = df[df['Brand_Ekstrak'].isin(top_brand)]

print(df_top['Brand_Ekstrak'].value_counts())
df_top['Brand_Ekstrak'].value_counts().plot(kind='bar')
plt.show()

plt.figure(figsize=(14,7))

sns.boxplot(
    data=df_top,
    x='Brand_Ekstrak',
    y='Harga_Produk'
)

plt.title("Distribusi Harga per Brand")
plt.xlabel("Brand")
plt.ylabel("Harga Produk")
plt.xticks(rotation=45)

plt.show()

"""> **Insight:** Samsung dan Apple memiliki rentang harga paling lebar karena menjual dari segmen mid-range hingga premium.  
> Brand seperti Infinix dan Tecno terkonsentrasi di segmen budget–mid-range (di bawah Rp 3 juta).

### 2.2 Jumlah Listing per Brand
Bar chart menunjukkan brand mana yang paling banyak menjual produk di marketplace.
"""

brand_count = df['Brand_Ekstrak'].value_counts().head(10)

brand_count

plt.figure(figsize=(12,6))

sns.barplot(
    x=brand_count.index,
    y=brand_count.values
)

plt.title("Top 10 Brand dengan Listing Terbanyak")
plt.xlabel("Brand")
plt.ylabel("Jumlah Listing")

plt.xticks(rotation=45)

plt.show()

"""> **Insight:** Samsung mendominasi jumlah listing terbanyak, diikuti Infinix dan Xiaomi.  
> Banyaknya listing tidak selalu berkorelasi dengan penjualan tertinggi, perlu dilihat efisiensi per listing.

### 2.3 Efisiensi Penjualan per Brand
Menghitung rata-rata unit terjual per listing untuk setiap brand untuk mengukur seberapa efektif tiap listing menghasilkan penjualan.
"""

brand_efficiency = (
    df.groupby('Brand_Ekstrak')['Valid_Terjual'].sum()
    /
    df['Brand_Ekstrak'].value_counts()
)

brand_efficiency = brand_efficiency.sort_values(ascending=False).head(10)

brand_efficiency

"""> **Insight:** Brand dengan listing sedikit tapi penjualan tinggi menunjukkan efisiensi pasar yang baik  
> artinya produk mereka lebih sering dibeli per listing dibanding brand dengan banyak listing tapi penjualan rendah.

---
## 3. Analisis Harga vs Penjualan

Bagian ini menguji apakah ada korelasi antara harga produk dan jumlah penjualan.  
**Hipotesis:** Apakah produk yang lebih murah selalu lebih laku?

### 3.1 Scatter Plot: Harga vs Jumlah Terjual
"""

# Scatter plot harga vs penjualan (menggunakan Produk_Terjual = data numerik aktual)
# Valid_Terjual adalah boolean, bukan angka penjualan — tidak tepat untuk korelasi

plt.figure(figsize=(10,6))

sns.scatterplot(
    data=df,
    x='Harga_Produk',
    y='Produk_Terjual',
    hue='Brand_Ekstrak',
    alpha=0.6,
    s=40
)

plt.title("Harga Produk vs Jumlah Terjual per Brand", fontsize=14)
plt.xlabel("Harga Produk (Rp)")
plt.ylabel("Jumlah Terjual")
plt.ticklabel_format(style='plain', axis='x')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=8)
plt.tight_layout()
plt.show()

"""### 3.2 Korelasi Harga vs Penjualan"""

# Hitung korelasi menggunakan Produk_Terjual (numerik)
correlation = df['Harga_Produk'].corr(df['Produk_Terjual'])
print(f"Korelasi Harga vs Jumlah Terjual: {correlation:.4f}")

if abs(correlation) < 0.1:
    print("→ Korelasi sangat lemah: harga TIDAK signifikan menentukan penjualan")
elif abs(correlation) < 0.3:
    print("→ Korelasi lemah")
elif abs(correlation) < 0.6:
    print("→ Korelasi sedang")
else:
    print("→ Korelasi kuat")

"""### 3.3 Tren Linear: Harga vs Penjualan"""

plt.figure(figsize=(10,6))

sns.regplot(
    data=df,
    x='Harga_Produk',
    y='Produk_Terjual',
    scatter_kws={'alpha':0.3, 's':20},
    line_kws={'color':'red', 'linewidth':2}
)

plt.title("Tren Linear: Harga Produk vs Jumlah Terjual", fontsize=14)
plt.xlabel("Harga Produk (Rp)")
plt.ylabel("Jumlah Terjual")
plt.ticklabel_format(style='plain', axis='x')
plt.tight_layout()
plt.show()

"""> **Insight:** Korelasi harga vs penjualan sangat lemah (mendekati 0), artinya **harga bukan faktor penentu utama penjualan**.  
> Faktor lain seperti brand trust, promosi marketplace, dan ulasan produk lebih berpengaruh terhadap keputusan beli konsumen.  
> Ini mengkonfirmasi bahwa analisis multi-faktor (composite score) lebih tepat untuk menilai performa brand.

---
## 4. Analisis Segmen Harga

Dataset dibagi ke dalam 4 segmen: **Budget** (< Rp 500rb), **Mid-Range** (Rp 500rb–2jt),  
**Upper-Mid** (Rp 2jt–7jt), dan **Premium** (> Rp 7jt).

### 4.1 Distribusi Produk per Segmen Harga
"""

sns.countplot(
    data=df,
    x='Segmen_Harga',
    order=df['Segmen_Harga'].value_counts().index
)

plt.title("Distribusi Segmen Harga")
plt.show()

"""### 4.2 Rata-rata Penjualan per Segmen"""

segment_sales = df.groupby('Segmen_Harga')['Valid_Terjual'].mean().sort_values()

segment_sales

# Rata-rata penjualan per segmen (menggunakan Produk_Terjual)
segment_sales_fix = df.groupby('Segmen_Harga')['Produk_Terjual'].mean().sort_values(ascending=False)

plt.figure(figsize=(8,5))
ax = sns.barplot(
    x=segment_sales_fix.index,
    y=segment_sales_fix.values,
    palette='viridis'
)
for container in ax.containers:
    ax.bar_label(container, fmt='%.0f', padding=3)
plt.title("Rata-rata Penjualan per Segmen Harga", fontsize=13)
plt.xlabel("Segmen Harga")
plt.ylabel("Rata-rata Unit Terjual")
plt.tight_layout()
plt.show()

"""### 4.3 Total Penjualan per Segmen"""

segment_sales = df.groupby('Segmen_Harga')['Valid_Terjual'].sum().sort_values(ascending=False)

segment_sales

plt.figure(figsize=(8,5))

sns.barplot(
    x=segment_sales.index,
    y=segment_sales.values
)

plt.title("Total Penjualan Berdasarkan Segmen Harga")
plt.xlabel("Segmen Harga")
plt.ylabel("Total Produk Terjual")

plt.show()

"""> **Insight:** Segmen Mid-Range mendominasi jumlah listing (±47%), mencerminkan pasar smartphone Indonesia  
> yang didominasi konsumen dengan anggaran Rp 500rb–2 juta.  
> Segmen Premium memiliki rata-rata penjualan per produk lebih rendah tapi nilai transaksi per unit jauh lebih tinggi.

---
## 5. Top Produk Terlaris
"""

# ── CEL 5: Normalisasi per Brand juga ────────────────────────
# Sama seperti platform, brand dengan listing banyak otomatis total terjual lebih tinggi
brand_listing  = df['Brand_Ekstrak'].value_counts()
brand_terjual  = df.groupby('Brand_Ekstrak')['Produk_Terjual'].sum()
brand_norm     = (brand_terjual / brand_listing).sort_values(ascending=False)

print("=== Efisiensi Brand: Rata-rata Terjual per Listing ===")
print(brand_norm.round(1).to_string())

plt.figure(figsize=(12, 5))
ax = plt.gca()
colors = ['#2ecc71' if v == brand_norm.max() else
          '#e74c3c' if v == brand_norm.min() else '#3498db'
          for v in brand_norm.values]
bars = ax.bar(brand_norm.index, brand_norm.values, color=colors, edgecolor='white')
for bar in bars:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3,
            f'{bar.get_height():.1f}', ha='center', fontsize=9)
ax.set_title("Efisiensi Brand: Rata-rata Terjual per Listing (Normalized)", fontsize=13)
ax.set_xlabel("Brand")
ax.set_ylabel("Unit Terjual per Listing")
plt.xticks(rotation=15)
plt.tight_layout()
plt.show()

# Top 10 produk dengan penjualan tertinggi
top_products = df.sort_values(by='Produk_Terjual', ascending=False).head(10)
top_products[['Produk', 'Brand_Ekstrak', 'E-Commerce', 'Harga_Produk', 'Produk_Terjual', 'Segmen_Harga']]

"""> **Insight:** Produk terlaris didominasi dari segmen mid-range dan budget, mengonfirmasi bahwa  
> keterjangkauan harga adalah faktor kunci volume penjualan di marketplace Indonesia.

---
## 6. Distribusi Harga Produk

### 6.1 Histogram Distribusi Harga
"""

plt.figure(figsize=(10,6))

sns.histplot(
    df['Harga_Produk'],
    bins=30,
    kde=True
)

plt.title("Distribusi Harga Smartphone")
plt.xlabel("Harga Produk")

plt.show()

"""### 6.2 Deteksi Outlier Harga"""

plt.figure(figsize=(12,4))

sns.boxplot(
    x=df['Harga_Produk']
)

plt.title("Deteksi Outlier Harga Produk")

plt.show()

"""> **Insight:** Distribusi harga right-skewed  mayoritas produk berada di bawah Rp 5 juta.  
> Beberapa outlier di atas Rp 15 juta merupakan produk flagship seperti iPhone dan Samsung Galaxy S series.

---
## 7. Analisis per Marketplace (Shopee, Lazada, Tokopedia)

### 7.1 Jumlah Listing per Marketplace
"""

ecommerce_count = df['E-Commerce'].value_counts()

sns.barplot(
    x=ecommerce_count.index,
    y=ecommerce_count.values
)

plt.title("Marketplace dengan Listing Terbanyak")
plt.show()

# Hitung total listing dan total terjual per platform
listing_count  = df['E-Commerce'].value_counts()
total_terjual  = df.groupby('E-Commerce')['Produk_Terjual'].sum()

normalized_sales = (total_terjual / listing_count).sort_values(ascending=False)

print("=== Perbandingan: Rata-rata Terjual per Listing ===")
for platform, val in normalized_sales.items():
    print(f"  {platform:12s}: {val:.1f} unit/listing")

print("\n=== Data Mentah===")
print(f"  Lazada  : {listing_count['Lazada']:>5} listing | {int(total_terjual['Lazada']):>8,} terjual")
print(f"  Shopee  : {listing_count['Shopee']:>5} listing | {int(total_terjual['Shopee']):>8,} terjual")
print(f"  Tokopedia: {listing_count['Tokopedia']:>4} listing | {int(total_terjual['Tokopedia']):>8,} terjual")

listing_count = df['E-Commerce'].value_counts()

market_sales = df.groupby('E-Commerce')['Valid_Terjual'].sum()

market_norm = (market_sales / listing_count).sort_values(ascending=False)

market_norm

# ── CEL 3: Chart normalisasi ─────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Chart kiri: total mentah (tidak adil)
ax1 = axes[0]
bars1 = ax1.bar(total_terjual.index, total_terjual.values,
                color=['#0f146d','#ee4d2d','#00aa5b'], edgecolor='white')
for bar in bars1:
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1000,
             f'{int(bar.get_height()):,}', ha='center', fontsize=10)
ax1.set_title("Total Penjualan (DATA MENTAH)\n⚠ Tidak adil — Lazada datanya lebih banyak",
              fontsize=11, color='#cc0000')
ax1.set_ylabel("Total Unit Terjual")
ax1.set_xlabel("Platform")

# Chart kanan: normalized (adil)
ax2 = axes[1]
colors_norm = ['#0f146d','#ee4d2d','#00aa5b']
# Sort untuk tampilan konsisten
norm_sorted = normalized_sales.reindex(['Lazada','Shopee','Tokopedia'])
bars2 = ax2.bar(norm_sorted.index, norm_sorted.values,
                color=colors_norm, edgecolor='white')
for bar in bars2:
    ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
             f'{bar.get_height():.1f}', ha='center', fontsize=11, fontweight='bold')
ax2.set_title("Rata-rata Terjual per Listing (NORMALIZED)\n✓ Perbandingan yang adil antar platform",
              fontsize=11, color='#006600')
ax2.set_ylabel("Unit Terjual per Listing")
ax2.set_xlabel("Platform")

plt.suptitle("Lazada vs Shopee vs Tokopedia: Perbandingan Adil", fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

"""### 7.2 Total & Rata-rata Penjualan per Marketplace"""

# Total penjualan per marketplace
market_sales = df.groupby('E-Commerce')['Produk_Terjual'].sum().sort_values(ascending=False)

plt.figure(figsize=(10,6))
ax = sns.barplot(x=market_sales.index, y=market_sales.values, palette='Blues_d')
for container in ax.containers:
    ax.bar_label(container, fmt='%.0f', padding=3)
plt.title("Total Penjualan per Marketplace", fontsize=13)
plt.xlabel("E-Commerce")
plt.ylabel("Total Unit Terjual")
plt.tight_layout()
plt.show()

print(market_sales)

"""### 7.3 Rata-rata Harga per Marketplace"""

market_price = df.groupby('E-Commerce')['Harga_Produk'].mean().sort_values(ascending=False)

market_price

plt.figure(figsize=(10,6))

sns.barplot(
    x=market_price.index,
    y=market_price.values
)

plt.title("Rata-rata Harga Produk per Marketplace")
plt.xlabel("Marketplace")
plt.ylabel("Rata-rata Harga")

plt.show()

"""### 7.4 Market Share Penjualan"""

total_sales = df.groupby('E-Commerce')['Produk_Terjual'].sum()
market_share = (total_sales / total_sales.sum()) * 100

plt.figure(figsize=(7,7))
plt.pie(
    market_share,
    labels=market_share.index,
    autopct='%1.1f%%',
    colors=['#ff6b6b','#4ecdc4','#45b7d1'],
    startangle=90
)
plt.title("Market Share Penjualan per Marketplace", fontsize=13)
plt.tight_layout()
plt.show()

print(market_share.round(2))

"""> **Insight:** Lazada mendominasi jumlah listing tetapi Shopee unggul dalam volume penjualan
> menunjukkan bahwa konversi listing ke penjualan di Shopee lebih tinggi, kemungkinan karena fitur flash sale dan promosi lebih agresif.  
> Rata-rata harga produk di Lazada lebih tinggi dibanding Shopee dan Tokopedia.

---
## 8. Heatmap Korelasi Antar Kolom Numerik

Heatmap menampilkan korelasi antara semua kolom numerik: `Harga_Produk`, `Produk_Terjual`, dan lainnya.  
Nilai mendekati 1 atau -1 menunjukkan korelasi kuat; mendekati 0 berarti tidak ada korelasi.
"""

numeric_df = df.select_dtypes(include=['int64', 'float64'])

numeric_df.head()

corr = numeric_df.corr()

corr

plt.figure(figsize=(10,8))
sns.heatmap(
    corr,
    annot=True,
    cmap='coolwarm',
    fmt='.2f',
    linewidths=0.5,
    square=True,
    annot_kws={'size':10}
)
plt.title("Heatmap Korelasi Kolom Numerik Dataset E-Commerce", fontsize=13)
plt.tight_layout()
plt.show()

"""> **Insight:** Korelasi antar kolom numerik umumnya lemah, mengkonfirmasi bahwa tidak ada satu variabel tunggal  
> yang secara kuat menentukan penjualan. Analisis multi-faktor (composite score) dengan mempertimbangkan  
> sentimen, harga, rating, dan penjualan secara bersamaan lebih representatif.

---
## 9. Simpan Hasil EDA
"""

# Simpan dataframe dengan kolom hasil EDA ke CSV
df.to_csv("eda_ecommerce.csv", index=False, encoding="utf-8-sig")
print("✅ File berhasil disimpan: eda_ecommerce_result.csv")
print(f"   Jumlah baris: {len(df)}")
print(f"   Jumlah kolom: {len(df.columns)}")
print(f"   Kolom: {df.columns.tolist()}")

"""---
## 10. Ringkasan Insight EDA E-Commerce

| No | Temuan | Implikasi |
|----|--------|-----------|
| 1 | Segmen Mid-Range dominasi 47% listing | Target utama pasar smartphone Indonesia |
| 2 | Korelasi harga vs penjualan ≈ -0.05 (sangat lemah) | Harga bukan penentu utama penjualan |
| 3 | Samsung listing terbanyak, Xiaomi penjualan tertinggi | Banyak listing ≠ penjualan tertinggi |
| 4 | Shopee: konversi penjualan per listing terbaik | Platform paling efektif untuk penjualan volume |
| 5 | Outlier harga di atas Rp 15jt = produk flagship | Perlu segmentasi terpisah untuk analisis premium |

"""